# Generated by Django 3.2.4 on 2024-04-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='select',
            field=models.CharField(choices=[('Artifical Intelligence', 'AI/ML'), ('Web dev', 'Web development'), ('Mobile dev', 'Mobile development'), ('Data science', 'Data science'), ('Robo', 'Robotics'), ('Digit market', 'Digital marketing'), ('Graphics design', 'Graphics designer')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(null=True, to='blog.Tag'),
        ),
    ]
