# Generated by Django 3.2.4 on 2024-05-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20240429_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='select',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Default Category Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
